#!/usr/bin/env python3
"""gen_db_providers.py — generates src/database/data/db_providers.inc.

Source of truth: the JetBrains "Complete Support" data-source dialog
(_docs/img.png, transcribed by the arguer-muse agent, 2026-09-09):
databases with full driver support, alphabetically. The image crop is
clipped at "PostgreSQL" (P); rows Q-Z are NOT invented here pending the
owner scrolling the dialog.

Row order matches the transcription (alphabetical). Rows are 6-tuples:
(slug, displayName, engine, defaultPort, family, note).

  * slug        : canonical lowercase-kebab key (derived mechanically).
  * displayName : verbatim from the dialog.
  * engine      : driver/engine key a future connector resolves (hand-
                  curated; "postgres", "mysql", "sqlserver", ...).
  * defaultPort : canonical wire port (0 = embedded / SDK-only / N/A);
                  only standard well-known defaults are set.
  * family      : coarse wire bucket (see DbProviderFamily in db_provider.h).
  * note        : caveat; None when nothing needs saying.

Regenerate:  python3 tools/gen_db_providers.py
"""

F_SQL = "DB_PROVIDER_FAMILY_SQL"          # relational SQL wire
F_SQLC = "DB_PROVIDER_FAMILY_SQL_COMPAT"  # SQL-ish analytics / warehouse
F_NOSQL = "DB_PROVIDER_FAMILY_NO_SQL"     # document / wide-column / kv
F_EMB = "DB_PROVIDER_FAMILY_EMBEDDED"     # embedded file/local engines

# (slug, displayName, engine, port, family, note)
ROWS = [
    ("amazon-aurora-mysql", "Amazon Aurora MySQL", "mysql", 3306, F_SQL,
     "AWS-managed MySQL-compatible"),
    ("amazon-documentdb", "Amazon DocumentDB", "mongodb", 27017, F_NOSQL,
     "MongoDB-wire compatible"),
    ("amazon-dynamodb", "Amazon DynamoDB", "dynamodb", 0, F_NOSQL,
     "AWS-native, SDK auth"),
    ("amazon-redshift", "Amazon Redshift", "redshift", 5439, F_SQLC,
     "PostgreSQL-derived"),
    ("apache-cassandra", "Apache Cassandra", "cassandra", 9042, F_NOSQL,
     None),
    ("apache-derby", "Apache Derby", "derby", 1527, F_EMB, None),
    ("apache-hive", "Apache Hive", "hive", 10000, F_SQLC, None),
    ("azure-sql-database", "Azure SQL Database", "sqlserver", 1433, F_SQL,
     None),
    ("azure-synapse-analytics", "Azure Synapse Analytics", "sqlserver", 1433,
     F_SQLC, "T-SQL wire"),
    ("clickhouse", "ClickHouse", "clickhouse", 8123, F_SQLC,
     "native HTTP JSON wire"),
    ("cockroachdb", "CockroachDB", "cockroachdb", 26257, F_SQL,
     "PostgreSQL-wire compatible"),
    ("couchbase-server", "Couchbase Server", "couchbase", 0, F_NOSQL,
     "port varies: kv 11210 / query 8093 / console 8091"),
    ("exasol", "Exasol", "exasol", 8563, F_SQLC, None),
    ("google-bigquery", "Google BigQuery", "bigquery", 0, F_SQLC,
     "Google Cloud SDK auth"),
    ("greenplum", "Greenplum", "greenplum", 5432, F_SQLC,
     "PostgreSQL-derived"),
    ("h2", "H2", "h2", 9092, F_EMB, None),
    ("hsqldb", "HSQLDB", "hsqldb", 9001, F_EMB, None),
    ("ibm-db2-luw", "IBM Db2 LUW", "db2", 50000, F_SQL, None),
    ("mariadb", "MariaDB", "mariadb", 3306, F_SQL,
     "MySQL-wire compatible"),
    ("microsoft-sql-server", "Microsoft SQL Server", "sqlserver", 1433, F_SQL,
     None),
    ("microsoft-sql-server-localdb", "Microsoft SQL Server LocalDB",
     "sqlserver", 0, F_EMB, "developer-local instance"),
    ("mongodb", "MongoDB", "mongodb", 27017, F_NOSQL, None),
    ("mysql", "MySQL", "mysql", 3306, F_SQL, None),
    ("oracle", "Oracle", "oracle", 1521, F_SQL, None),
    ("postgresql", "PostgreSQL", "postgres", 5432, F_SQL, None),
]

OUT = "src/database/data/db_providers.inc"


def main() -> None:
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(
            "// ============================================================================\n"
            "// DATABASE PROVIDERS: JetBrains Complete Support data sources\n"
            "//               — src/database/data/db_providers.inc\n"
            "// GENERATED by tools/gen_db_providers.py — do not hand-edit; regenerate instead.\n"
            "//\n"
            f"// {len(ROWS)} DbProviderSlot rows transcribed from the JetBrains data-source\n"
            "// dialog (_docs/img.png). Alphabetical; the source image is clipped at\n"
            "// PostgreSQL (P) — rows Q-Z pending the owner. Included ONLY by\n"
            "// db_provider.c (single translation unit), satisfying the Rule 3\n"
            "// slot-record co-location; see ;;INTENTION in db_provider.c.\n"
            "//\n"
            "// defaultPort == 0 means embedded / SDK-only / N/A — no canonical wire port.\n"
            "// ============================================================================\n"
            "static const DbProviderSlot kDbProviders[] = {\n\n"
        )
        for slug, display, engine, port, family, note in ROWS:
            note_lit = '"%s"' % note if note else "NULL"
            f.write(
                "    {\n"
                '        "%s",\n'
                '        "%s",\n'
                '        "%s",\n'
                "        %d,\n"
                "        %s,\n"
                "        %s,\n"
                "    },\n" % (slug, display, engine, port, family, note_lit)
            )
        f.write("};\n")
    print(f"wrote {OUT} with {len(ROWS)} rows")


if __name__ == "__main__":
    main()