#!/usr/bin/env python3
"""gen_providers.py — regenerate the AiProvider directory fragments.

Source of truth for projects/api-haven/src/ai/data/*.inc:
  * display names: the upstream OpenRouter provider directory — the vexgraph
    master list of ~206 endpoint variants PLUS the canonical 105-provider
    official list (https://openrouter.ai/api/v1/providers) for base vendors,
    PLUS two intentional rows (openrouter: the normalized gateway this
    directory mirrors; ollama-local: the sibling of Ollama Cloud). Kept
    verbatim so the table reads like the ecosystem it models.
  * slugs: canonicalized from official provider list where the entry matches,
    else derived from the name.
  * baseUrl: filled ONLY where the native endpoint is verified/publicly
    documented; NULL means "native endpoint unverified — resolve via family
    default or a router override" (see ai_provider.c ;;INTENTION).
  * region: explicit bucket from the entry (China/Europe variants) or the
    official headquarters country.

Usage:  python3 tools/gen_providers.py   (run from the api-haven repo root)
Output: rewrites src/ai/data/providers_global.inc / providers_china.inc /
        providers_europe.inc

REGIONS are mechanical buckets only; the AiProvider table class treats them
as one flat directory (count/at/get span all fragments).
"""

# (slug, displayName, family, auth, baseUrl, note, region)
# region: GLOBAL | CHINA | EUROPE   (OTHER rows go to GLOBAL)

F_OPENAI = "AI_PROVIDER_FAMILY_OPENAI_COMPAT"
F_ANTHR = "AI_PROVIDER_FAMILY_ANTHROPIC"
F_ROUTER = "AI_PROVIDER_FAMILY_ROUTER"
F_NATIVE = "AI_PROVIDER_FAMILY_NATIVE"
F_LOCAL = "AI_PROVIDER_FAMILY_LOCAL"

A_BEARER = "AI_PROVIDER_AUTH_BEARER"
A_APIKEY = "AI_PROVIDER_AUTH_API_KEY"
A_XKEY = "AI_PROVIDER_AUTH_X_API_KEY"
A_NONE = "AI_PROVIDER_AUTH_NONE"
A_SPECIAL = "AI_PROVIDER_AUTH_SPECIAL"

R_G = "AI_PROVIDER_REGION_GLOBAL"
R_C = "AI_PROVIDER_REGION_CHINA"
R_E = "AI_PROVIDER_REGION_EUROPE"
R_O = "AI_PROVIDER_REGION_OTHER"

ROWS = [
    # --- custom / router gateways -----------------------------------------
    ("custom-openai", "Custom OpenAI-compatible provider", F_OPENAI, A_BEARER, None,
     "user-supplied base URL; override via AiChat_setBaseUrl", R_G),
    ("302ai", "302.AI", F_ROUTER, A_BEARER, "https://302.ai/api/v1",
     "aggregator gateway", R_G),
    ("abacus", "Abacus", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("abliteration", "abliteration.ai", F_OPENAI, A_BEARER, None,
     "uncensored-model host; endpoint unverified", R_G),
    ("above-dev", "above.dev", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("agent-router", "AgentRouter", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("agnes-ai", "Agnes AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("ai-router", "AI-ROUTER", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("aiand", "ai&", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("aihubmix", "AIHubMix", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("aixy", "Aixy", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("aki-io", "AKI.IO", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("anyapi", "AnyAPI", F_ROUTER, A_BEARER, None,
     "aggregator gateway", R_G),
    ("atomic-chat", "Atomic Chat", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("auriko", "Auriko", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("berget-ai", "Berget.AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("blue-claw", "Blue Claw", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("bothub", "Bothub", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("charm-hyper", "Charm Hyper", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("claudinio", "Claudinio", F_ANTHR, A_XKEY, None,
     "Claude-compatible mirror; endpoint unverified", R_G),
    ("cline-pass", "ClinePass", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("cross-model", "CrossModel", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("dao-xe", "DaoXE", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("devpass", "DevPass (LLM Gateway)", F_ROUTER, A_BEARER, None,
     "LLM gateway", R_G),
    ("d-inference", "DInference", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("eb-cloud", "EBCloud", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("echo", "Echo", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("eden-ai", "Eden AI", F_ROUTER, A_BEARER, None,
     "aggregator gateway", R_G),
    ("empiriolabs-ai", "EmpirioLabs AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("fast-router", "FastRouter", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("free-model", "FreeModel", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("frog-bot", "FrogBot", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("green-pt", "GreenPT", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("helicone", "Helicone", F_ROUTER, A_BEARER, "https://oai.helicone.ai/v1",
     "LLM observability gateway", R_G),
    ("i-flow", "iFlow", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("impossibl", "Impossibl", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("inference", "Inference", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("infer-x", "InferX", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("jalapeno-cloud", "Jalapeno Cloud", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("jiekou-ai", "Jiekou.AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("kenari", "Kenari", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("kilo-gateway", "Kilo Gateway", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("kosmik-compute", "Kosmik Compute", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("llama", "Llama", F_OPENAI, A_BEARER, None,
     "Meta Llama served via gateway/GPU hosts", R_G),
    ("llm-gateway", "LLM Gateway", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("llm-tech", "LLM Tech", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("llmtr", "LLMTR", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("long-cat", "LongCat", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("lucid-query", "LucidQuery", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("lynkr", "Lynkr", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("meganova", "Meganova", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("merge-gateway", "Merge Gateway", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("mixlayer", "Mixlayer", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("moark", "Moark", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("model-oracle-ai", "Model Oracle AI", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("modelis", "Modelis", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("nan", "NaN", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("nano-gpt", "NanoGPT", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("near-ai-cloud", "NEAR AI Cloud", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("neon", "Neon", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("neo-smith", "NeoSmith", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("neuralwatt", "Neuralwatt", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("nova", "Nova", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("ofox", "Ofox", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("open-reason", "OpenReason", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("opper", "Opper", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("orca-router", "OrcaRouter", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("pendra", "Pendra", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("pioneer", "Pioneer", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("privatemode-ai", "Privatemode AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("qi-hang", "QiHang", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("qiniu", "Qiniu", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("qvac", "QVAC", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("regolo-ai", "Regolo AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("requesty", "Requesty", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("routing-run", "routing.run", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("run-infra", "RunInfra", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("salad-cloud-ai-gateway", "SaladCloud AI Gateway", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("sarvam-ai", "Sarvam AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("sc-net-token-plan", "SCNet Token Plan", F_OPENAI, A_BEARER, None,
     "token plan variant", R_G),
    ("scx-ai", "SCX.ai", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("stackit", "STACKIT", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("standard-compute", "Standard Compute", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("subconscious", "Subconscious", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("submodel", "submodel", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("synthetic", "Synthetic", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("tencent-tokenhub", "Tencent TokenHub", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("tensor-x", "TensorX", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("the-grid-ai", "The Grid AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("tinfoil", "Tinfoil", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("token-go", "TokenGo", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("token-router", "TokenRouter", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("trusted-router", "TrustedRouter", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("umans-ai", "Umans AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("umans-ai-coding-plan", "Umans AI Coding Plan", F_OPENAI, A_BEARER, None,
     "coding plan variant", R_G),
    ("uno-router", "UnoRouter", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),
    ("vancine", "Vancine", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("vivgrid", "Vivgrid", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("xpersona", "Xpersona", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("zeldoc", "Zeldoc", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("zenifra", "Zenifra", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("zen-mux", "ZenMux", F_ROUTER, A_BEARER, None,
     "router gateway", R_G),

    # --- US-hosted majors ---------------------------------------------------
    ("openai", "OpenAI", F_OPENAI, A_BEARER, "https://api.openai.com/v1",
     "reference OpenAI-compatible endpoint", R_G),
    ("anthropic", "Anthropic", F_ANTHR, A_XKEY, "https://api.anthropic.com/v1",
     "native Messages API; x-api-key + anthropic-version headers", R_G),
    ("xai", "xAI", F_OPENAI, A_BEARER, "https://api.x.ai/v1",
     "Grok family", R_G),
    ("groq", "Groq", F_OPENAI, A_BEARER, "https://api.groq.com/openai/v1",
     "LPU inference", R_G),
    ("deepseek", "DeepSeek", F_OPENAI, A_BEARER, "https://api.deepseek.com/v1",
     "deepseek-chat / deepseek-reasoner", R_C),
    ("openrouter", "OpenRouter", F_ROUTER, A_BEARER, "https://openrouter.ai/api/v1",
     "the normalized gateway this directory mirrors", R_G),
    ("meta", "Meta", F_OPENAI, A_BEARER, None,
     "Llama served via gateway/GPU hosts", R_G),
    ("nvidia", "Nvidia", F_OPENAI, A_BEARER, "https://integrate.api.nvidia.com/v1",
     "NVIDIA NIM inference", R_G),
    ("perplexity", "Perplexity", F_OPENAI, A_BEARER, "https://api.perplexity.ai",
     "sonar family", R_G),
    ("perplexity-agent", "Perplexity Agent", F_OPENAI, A_BEARER, "https://api.perplexity.ai",
     "agent endpoint", R_G),
    ("together", "Together AI", F_OPENAI, A_BEARER, "https://api.together.xyz/v1",
     "serverless inference", R_G),
    ("cerebras", "Cerebras", F_OPENAI, A_BEARER, "https://api.cerebras.ai/v1",
     "WSE inference", R_G),
    ("fireworks", "Fireworks AI", F_OPENAI, A_BEARER, "https://api.fireworks.ai/inference/v1",
     "serverless inference", R_G),
    ("deepinfra", "Deep Infra", F_OPENAI, A_BEARER, "https://api.deepinfra.com/v1/openai",
     "serverless inference", R_G),
    ("friendli", "Friendli", F_OPENAI, A_BEARER, "https://api.friendli.ai/serverless/v1",
     "serverless inference", R_G),
    ("cohere", "Cohere", F_OPENAI, A_BEARER, None,
     "native /v1 chat; OpenAI-compat at /compatibility/v1", R_G),
    ("hugging-face", "Hugging Face", F_OPENAI, A_BEARER, "https://router.huggingface.co/v1",
     "unified inference router", R_G),
    ("databricks", "Databricks", F_OPENAI, A_BEARER, None,
     "per-workspace serving endpoint required", R_G),
    ("modal", "Modal", F_OPENAI, A_BEARER, None,
     "per-app workspace endpoint required", R_G),
    ("ambient", "Ambient", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("arcee-ai", "Arcee", F_OPENAI, A_BEARER, None,
     "Arcee AI; endpoint unverified", R_G),
    ("atlas-cloud", "AtlasCloud", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("avian", "Avian", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("baseten", "Baseten", F_OPENAI, A_BEARER, None,
     "per-model deployment endpoint required", R_G),
    ("chutes", "Chutes", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("clarifai", "Clarifai", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("cloudflare", "Cloudflare AI Gateway", F_ROUTER, A_BEARER, None,
     "per-account gateway URL required", R_G),
    ("cloudflare-workers-ai", "Cloudflare Workers AI", F_OPENAI, A_BEARER, None,
     "per-account /ai/v1 URL required", R_G),
    ("coreweave", "CoreWeave", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("cosine", "Cosine", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("crucible", "Crucible", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("darkbloom", "Darkbloom", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("decart", "Decart", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("featherless", "Featherless", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("gmicloud", "GMI Cloud", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("google-ai-studio", "Google AI Studio", F_NATIVE, A_BEARER, None,
     "Gemini native; OpenAI-compat at /v1beta/openai/", R_G),
    ("google-vertex", "Vertex", F_NATIVE, A_SPECIAL, None,
     "Google Vertex AI — OAuth/service-account adapter required", R_G),
    ("inception", "Inception", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("inferact-vllm", "Inferact vLLM", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("inference-net", "InferenceNet", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("infermatic", "Infermatic", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("inflection", "Inflection", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("io-net", "IO.NET", F_OPENAI, A_BEARER, None,
     "GPU cloud; endpoint unverified", R_G),
    ("ionstream", "Ionstream", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("krea", "Krea", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("mancer", "Mancer", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("mara", "Mara", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("modelrun", "ModelRun", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("modular", "Modular", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("morph", "Morph", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("novita", "NovitaAI", F_OPENAI, A_BEARER, "https://api.novita.ai/v3/openai",
     "serverless inference", R_G),
    ("ollama-cloud", "Ollama Cloud", F_OPENAI, A_BEARER, None,
     "hosted Ollama; local sibling at http://localhost:11434/v1", R_G),
    ("ollama", "Ollama (local)", F_LOCAL, A_NONE, "http://localhost:11434/v1",
     "local runtime, no auth", R_G),
    ("lm-studio", "LMStudio", F_LOCAL, A_NONE, "http://localhost:1234/v1",
     "local runtime, no auth", R_G),
    ("open-inference", "OpenInference", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("parasail", "Parasail", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("perceptron", "Perceptron", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("phala", "Phala", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("poolside", "Poolside", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("primeintellect", "PrimeIntellect", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("quiver", "Quiver", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("recraft", "Recraft", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("reka", "Reka", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("relace", "Relace", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("runway", "Runway", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("sail-research", "Sail Research", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("samba-nova", "SambaNova", F_OPENAI, A_BEARER, "https://api.sambanova.ai/v1",
     "RDU inference", R_G),
    ("sourceful", "Sourceful", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("stealth", "Stealth", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("switchpoint", "Switchpoint", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("tenstorrent", "Tenstorrent", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("upstage", "Upstage", F_OPENAI, A_BEARER, "https://api.upstage.ai/v1/solar",
     "Solar family", R_G),
    ("venice", "Venice AI", F_OPENAI, A_BEARER, "https://api.venice.ai/api/v1",
     "private inference", R_G),
    ("wafer", "Wafer", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("watsonx-ai", "watsonx.ai", F_NATIVE, A_SPECIAL, None,
     "IBM watsonx — IAM token adapter required", R_G),
    ("weights-biases", "Weights & Biases", F_NATIVE, A_SPECIAL, None,
     "W&B launch gateway", R_G),
    ("snowflake-cortex", "Snowflake Cortex", F_NATIVE, A_SPECIAL, None,
     "Cortex — Snowflake OAuth adapter required", R_G),
    ("sap-ai-core", "SAP AI Core", F_NATIVE, A_SPECIAL, None,
     "per-deployment endpoint; SAP auth adapter required", R_G),
    ("github-copilot", "GitHub Copilot", F_OPENAI, A_BEARER,
     "https://api.githubcopilot.com/chat/completions",
     "GitHub OAuth token", R_G),
    ("gitlab-duo", "GitLab Duo", F_NATIVE, A_SPECIAL, None,
     "GitLab Duo API token + /api/v4/ai endpoints", R_G),
    ("poe", "Poe", F_NATIVE, A_BEARER, "https://api.poe.com",
     "Poe bot API", R_G),
    ("v0", "v0", F_NATIVE, A_SPECIAL, None,
     "Vercel v0 — bespoke endpoint", R_G),
    ("azure", "Azure", F_OPENAI, A_APIKEY, None,
     "per-resource endpoint; api-key header + api-version", R_G),
    ("azure-cognitive-services", "Azure Cognitive Services", F_OPENAI, A_APIKEY, None,
     "per-resource endpoint; api-key header + api-version", R_G),
    ("amazon-bedrock", "Amazon Bedrock", F_NATIVE, A_SPECIAL, None,
     "AWS SigV4 signing adapter required", R_G),
    ("claude-on-aws", "Claude Platform on AWS", F_ANTHR, A_SPECIAL, None,
     "Bedrock-hosted Claude — SigV4 adapter required", R_G),
    ("vertex-anthropic", "Vertex (Anthropic)", F_ANTHR, A_SPECIAL, None,
     "Vertex-hosted Claude — OAuth/service-account adapter required", R_G),
    ("crusoe", "Crusoe", F_OPENAI, A_BEARER, None,
     "GPU cloud; endpoint unverified", R_G),
    ("digitalocean", "DigitalOcean", F_OPENAI, A_BEARER, None,
     "agent inference; endpoint unverified", R_G),
    ("hetzner", "Hetzner", F_OPENAI, A_BEARER, "https://api.hetzner.ai/v1",
     "AI endpoints", R_E),
    ("vultr", "Vultr", F_OPENAI, A_BEARER, None,
     "Vultr Inferencing — project endpoint required", R_G),
    ("akashml", "AkashML", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("aion-labs", "AionLabs", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("ai21", "AI21", F_OPENAI, A_BEARER, None,
     "Jamba family; endpoint unverified", R_G),
    ("amd", "AMD", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("gpu-network", "GPU Network", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("hirsh", "Hirsh", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("infermatic-ai", "Infermatic AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("liquid", "Liquid", F_OPENAI, A_BEARER, None,
     "LFM family; endpoint unverified", R_G),
    ("nous-research", "Nous Research", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("seed", "Seed", F_OPENAI, A_BEARER, None,
     "Bytedance Seed; endpoint unverified", R_G),
    ("thinking-machines", "Thinking Machines", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("sakana", "Sakana AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),

    # --- stragglers from the master list (verified against it 2026-09-09) ----
    ("cloudferro-sherlock", "CloudFerro Sherlock", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_E),
    ("crof-ai", "CrofAI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("hpc-ai", "HPC-AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("itera-compute", "IteraCompute", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),
    ("lilac", "Lilac", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_G),

    # --- China vendors -------------------------------------------------------
    ("alibaba", "Alibaba", F_OPENAI, A_BEARER,
     "https://dashscope.aliyuncs.com/compatible-mode/v1",
     "DashScope compatible-mode (Qwen)", R_C),
    ("alibaba-china", "Alibaba (China)", F_OPENAI, A_BEARER,
     "https://dashscope.aliyuncs.com/compatible-mode/v1",
     "DashScope compatible-mode (Qwen), CN mirror", R_C),
    ("alibaba-coding-plan", "Alibaba Coding Plan", F_OPENAI, A_BEARER,
     "https://dashscope.aliyuncs.com/compatible-mode/v1",
     "coding plan variant", R_C),
    ("alibaba-token-plan", "Alibaba Token Plan", F_OPENAI, A_BEARER,
     "https://dashscope.aliyuncs.com/compatible-mode/v1",
     "token plan variant", R_C),
    ("baidu", "Baidu", F_OPENAI, A_BEARER, None,
     "Ernie; endpoint unverified", R_C),
    ("bailing", "Bailing", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_C),
    ("coral-bricks", "CoralBricks", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_C),
    ("cortecs", "Cortecs", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_C),
    ("d-run", "D.Run (China)", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_C),
    ("kuae-coding-plan", "KUAE Cloud Coding Plan", F_OPENAI, A_BEARER, None,
     "coding plan variant", R_C),
    ("minimax-io", "MiniMax (minimax.io)", F_OPENAI, A_BEARER,
     "https://api.minimax.io/v1",
     "MiniMax international", R_G),
    ("minimaxi-com", "MiniMax (minimaxi.com)", F_OPENAI, A_BEARER,
     "https://api.minimaxi.com/v1",
     "MiniMax China", R_C),
    ("minimax-io-token-plan", "MiniMax Token Plan (minimax.io)", F_OPENAI, A_BEARER,
     "https://api.minimax.io/v1",
     "token plan variant", R_G),
    ("minimaxi-com-token-plan", "MiniMax Token Plan (minimaxi.com)", F_OPENAI, A_BEARER,
     "https://api.minimaxi.com/v1",
     "token plan variant", R_C),
    ("model-scope", "ModelScope", F_OPENAI, A_BEARER,
     "https://api.modelscope.cn/v1",
     "Alibaba ModelScope", R_C),
    ("moonshot-ai", "Moonshot AI", F_OPENAI, A_BEARER,
     "https://api.moonshot.ai/v1",
     "Kimi international", R_G),
    ("moonshot-ai-china", "Moonshot AI (China)", F_OPENAI, A_BEARER,
     "https://api.moonshot.cn/v1",
     "Kimi CN mirror", R_C),
    ("kimi-for-coding", "Kimi For Coding", F_OPENAI, A_BEARER,
     "https://api.moonshot.cn/v1",
     "Moonshot coding plan (Kimi)", R_C),
    ("nex-agi", "Nex AGI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_C),
    ("sense-nova", "SenseNova (China)", F_OPENAI, A_BEARER, None,
     "SenseTime; endpoint unverified", R_C),
    ("siliconflow", "SiliconFlow", F_OPENAI, A_BEARER,
     "https://api.siliconflow.cn/v1",
     "serverless inference (CN)", R_C),
    ("siliconflow-china", "SiliconFlow (China)", F_OPENAI, A_BEARER,
     "https://api.siliconflow.cn/v1",
     "serverless inference (CN)", R_C),
    ("stepfun", "StepFun (Global)", F_OPENAI, A_BEARER,
     "https://api.stepfun.com/v1",
     "StepFun international", R_G),
    ("stepfun-china", "StepFun (China)", F_OPENAI, A_BEARER,
     "https://api.stepfun.com/v1",
     "StepFun CN mirror", R_C),
    ("stepfun-step-plan", "StepFun Step Plan (Global)", F_OPENAI, A_BEARER,
     "https://api.stepfun.com/v1",
     "token plan variant", R_G),
    ("stepfun-step-plan-china", "StepFun Step Plan (China)", F_OPENAI, A_BEARER,
     "https://api.stepfun.com/v1",
     "token plan variant", R_C),
    ("streamlake", "StreamLake", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_C),
    ("tencent", "Tencent", F_OPENAI, A_BEARER,
     "https://api.hunyuan.cloud.tencent.com/v1",
     "Hunyuan OpenAI-compat", R_C),
    ("tencent-coding-plan", "Tencent Coding Plan (China)", F_OPENAI, A_BEARER,
     "https://api.hunyuan.cloud.tencent.com/v1",
     "coding plan variant", R_C),
    ("tencent-token-plan", "Tencent Token Plan", F_OPENAI, A_BEARER,
     "https://api.hunyuan.cloud.tencent.com/v1",
     "token plan variant", R_C),
    ("volcengine-ark", "Volcengine Ark", F_OPENAI, A_BEARER,
     "https://ark.cn-beijing.volces.com/api/v3",
     "ByteDance Ark", R_C),
    ("volcengine-ark-coding-plan", "Volcengine Ark Coding Plan", F_OPENAI, A_BEARER,
     "https://ark.cn-beijing.volces.com/api/v3",
     "coding plan variant", R_C),
    ("xiaomi", "Xiaomi", F_OPENAI, A_BEARER, None,
     "MiLM; endpoint unverified", R_C),
    ("xiaomi-token-plan-china", "Xiaomi Token Plan (China)", F_OPENAI, A_BEARER, None,
     "token plan variant", R_C),
    ("xiaomi-token-plan-europe", "Xiaomi Token Plan (Europe)", F_OPENAI, A_BEARER, None,
     "token plan variant", R_E),
    ("xiaomi-token-plan-singapore", "Xiaomi Token Plan (Singapore)", F_OPENAI, A_BEARER, None,
     "token plan variant", R_O),
    ("zhipu-ai", "Zhipu AI", F_OPENAI, A_BEARER,
     "https://open.bigmodel.cn/api/paas/v4",
     "GLM family (CN)", R_C),
    ("zhipu-ai-coding-plan", "Zhipu AI Coding Plan", F_OPENAI, A_BEARER,
     "https://open.bigmodel.cn/api/paas/v4",
     "coding plan variant", R_C),
    ("z-ai", "Z.AI", F_OPENAI, A_BEARER,
     "https://api.z.ai/api/paas/v4",
     "Zhipu rebrand (international)", R_G),
    ("z-ai-coding-plan", "Z.AI Coding Plan", F_OPENAI, A_BEARER,
     "https://api.z.ai/api/paas/v4",
     "coding plan variant", R_G),

    # --- Europe --------------------------------------------------------------
    ("mistral", "Mistral", F_OPENAI, A_BEARER, "https://api.mistral.ai/v1",
     "Le Chat API, OpenAI-compat", R_E),
    ("inceptron", "Inceptron", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_E),
    ("nebius-token-factory", "Nebius Token Factory", F_OPENAI, A_BEARER,
     "https://api.studio.nebius.ai/v1",
     "Nebius AI Studio", R_E),
    ("nextbit", "NextBit", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_E),
    ("scaleway", "Scaleway", F_OPENAI, A_BEARER,
     "https://api.scaleway.ai/v1",
     "Scaleway AI endpoints", R_E),
    ("infomaniak", "Infomaniak", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_E),
    ("ovhcloud-ai-endpoints", "OVHcloud AI Endpoints", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_E),
    ("evroc", "evroc", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_E),
    ("klok-integration", "klokintegration.se", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_E),
    ("green-ai", "Green AI", F_OPENAI, A_BEARER, None,
     "endpoint unverified", R_E),
]

BUCKETS = {
    "GLOBAL": [],
    "CHINA": [],
    "EUROPE": [],
}
for row in ROWS:
    region = row[6]
    key = {"AI_PROVIDER_REGION_GLOBAL": "GLOBAL",
           "AI_PROVIDER_REGION_CHINA": "CHINA",
           "AI_PROVIDER_REGION_EUROPE": "EUROPE",
           "AI_PROVIDER_REGION_OTHER": "GLOBAL"}[region]
    BUCKETS[key].append(row)

HEADER = """// ============================================================================
// PROVIDERS: %(bucket)s — %(path)s
// GENERATED by tools/gen_providers.py — do not hand-edit; regenerate instead.
//
// %(count)u AiProviderSlot rows of the %(bucket)s region bucket. This fragment
// is included ONLY by ai_provider.c (single translation unit), satisfying the
// Rule 3 slot-record co-location; see ;;INTENTION in ai_provider.c.
//
// baseUrl == NULL means "native endpoint unverified" — resolve via the
// family default or a router override (see ai_provider.h + ai_chat.h).
// ============================================================================
static const AiProviderSlot kAiProviders%(bucket)s[] = {
"""

FOOTER = """};

"""

def emit(path, bucket, rows):
    out = []
    header = HEADER % {"bucket": bucket.title(), "path": path, "count": len(rows)}
    out.append(header)
    # Stable sort: providers with a verified baseUrl first, then alphabetical.
    rows_sorted = sorted(rows, key=lambda r: (r[4] is None, r[0]))
    for (slug, name, family, auth, base, note, _region) in rows_sorted:
        base_lit = '"%s"' % base if base is not None else "NULL"
        note_lit = '"%s"' % note if note else "NULL"
        out.append("    {\n"
                   "        \"%s\",\n"
                   "        \"%s\",\n"
                   "        %s,\n"
                   "        %s,\n"
                   "        %s,\n"
                   "        %s,\n"
                   "        %s,\n"
                   "    }," % (slug, name, base_lit, family, auth, "AI_PROVIDER_REGION_" + bucket.upper() if False else _region, note_lit))
    out.append(FOOTER)
    with open(path, "w") as f:
        f.write("\n".join(out))
    print("wrote %s with %u rows" % (path, len(rows_sorted)))

emit("src/ai/data/providers_global.inc", "GLOBAL", BUCKETS["GLOBAL"])
emit("src/ai/data/providers_china.inc", "CHINA", BUCKETS["CHINA"])
emit("src/ai/data/providers_europe.inc", "EUROPE", BUCKETS["EUROPE"])
print("TOTAL rows:", len(ROWS))